---

# The Infrastructure Persistant storage using dynamic provisioning.
# With dynamic provisioning you only need to provide the PVC and specify
# the storage class.
#
# oc process -f infra-pvc-dynamic.yaml | oc create -n $OC_INFRA_PROJECT -f -
# oc delete pvc --selector template=infra-pvc-dynamic -n $OC_INFRA_PROJECT

kind: Template
apiVersion: v1
metadata:
  name: infra-persistence-dynamic
  annotations:
    description: Squonk Infrastructure Persistence using dynamic provisioning
    tags: squonk,infra,pv,pvc
labels:
  template: infra-pvc-dynamic

parameters:

- name: STORAGE_CLASS
  value: standard

- name: RABBITMQ_VOLUME_SIZE
  value: 1Gi

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: rabbitmq-claim
    labels:
      application: rabbitmq
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${RABBITMQ_VOLUME_SIZE}
    storageClassName: ${STORAGE_CLASS}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql-claim
    labels:
      application: postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"
    storageClassName: ${STORAGE_CLASS}


