---

# The Infrastructure Persistant storage.
#
# oc process -f infra-pvc-nfs.yaml | oc create -n $OC_INFRA_PROJECT -f -
# oc delete pv,pvc --selector template=infra-pvc-nfs -n $OC_INFRA_PROJECT

kind: Template
apiVersion: v1
metadata:
  name: infra-persistence-nfs
  annotations:
    description: Squonk Infrastructure Persistence using NFS
    tags: squonk,infra,pv,pvc
labels:
  template: infra-pvc-nfs

parameters:

- name: INFRA_NAMESPACE
  value: openrisknet-infra

- name: NFS_SERVER

- name: NFS_PATH
  value: /exports

- name: RABBITMQ_VOLUME_SIZE
  value: 1Gi

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: pv-rabbitmq
    labels:
      application: rabbitmq
  spec:
    capacity:
      storage: ${RABBITMQ_VOLUME_SIZE}
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-rabbitmq
    claimRef:
      name: rabbitmq-claim
      namespace: ${INFRA_NAMESPACE}

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: pv-postgresql
    labels:
      application: postgresql
  spec:
    capacity:
      storage: ${POSTGRESQL_VOLUME_SIZE}
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-postgresql
    claimRef:
      name: postgresql-claim
      namespace: ${INFRA_NAMESPACE}

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: rabbitmq-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: rabbitmq
  spec:
    volumeName: pv-rabbitmq
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${RABBITMQ_VOLUME_SIZE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: postgresql
  spec:
    volumeName: pv-postgresql
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"


