---

certbot_domain: "{{ hostvars[groups['masters'][0]].openshift_master_cluster_public_hostname }}"
certbot_email: tdudgeon@informaticsmatters.com
certbot_renew_command: "certbot certonly -n --standalone -d {{ certbot_domain }} --agree-tos --email {{ certbot_email }}"
