apiVersion: v1
kind: Service
metadata:
  name: orn-registry # often the same as the name of the app
  namespace: orn-infra
  labels:
    app: orn-registry # often the same as the name of the app
spec:
  ports:
  - port: 8085 # port at the service ip
    targetPort: 8085 # port on the container as per the deploymnet
    protocol: TCP
    name: http
  selector:
    app: orn-registry # often the same as the name of the app
