apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chemidconvert-ingress
  namespace: openrisknet
  annotations:
    kubernetes.io/ingress.class: "traefik" # this is supposed to tell the GCE default inress controller to ingore this
spec:
  rules:
  - host: chemidconvert.cloud.douglasconnect.com
    http:
      paths:
      - backend:
          serviceName: chemidconvert
          servicePort: 8080
