apiVersion: v1
kind: Service
metadata:
  name: chemidconvert
  namespace: chemidconvert
  labels:
    app: chemidconvert
  annotations:
    openrisknet-static-services: http://chemidconvert.chemidconvert.svc.cluster.local:8080/v1/swagger.json
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: chemidconvert
