---

# A certbot/let's encrypt renewal playbook.
# This should only result in actions when the
# certificate is nearing its expiry.

- import_tasks: include-vars.yml
- import_tasks: install-certbot.yml
- import_tasks: renew.yml
