---

# Try to renew the certificates (typically using certbot's certonly option).
# To determine whether certificates have been renewed we need to check the
# stdout of the command. If certificates were not renewed you'll see something
# like this in the output stream...
#
#   Cert not yet due for renewal
#
# And, if successful, you should see something like: -
#
#   Congratulations!

# In order for this to work with the more recent certbot I believe we
# need to suspend the master's API service during the renewal...

# Don't fail if stopping the service fails.
# This can occur on the DEV-site (an OKD 3.11 deployment)
- name: Stop Master API service
  service:
    name: origin-master-api.service
    state: stopped
  ignore_errors: yes

- name: Renew an existing certificate
  shell: "{{ certbot_renew_command }}"
  register: certbot_result
  become: true

- name: Set certificate renewal fact
  set_fact:
    certificates_renewed: true
  when: '"Congratulations" in certbot_result.stdout'

- name: Start Master API service
  service:
    name: origin-master-api.service
    state: started
  ignore_errors: yes
