---

# Copy certs (if they were renewed)

- name: Copy certificates (from remote)
  fetch:
    src: "{{ certbot_src_dir }}/{{ item }}"
    dest: "{{ local_cert_dir }}/"
    flat: true
  become: true
  loop:
  - cert.pem
  - chain.pem
  - fullchain.pem
  - privkey.pem
  when: certificates_renewed is defined
