---

# oc process -f bridgedb.yaml | oc create -f -
# oc delete all --selector template=bridgedb

kind: Template
apiVersion: v1
metadata:
  name: bridgedbfull
  annotations:
    description: BridgeDB
    tags: bridge
labels:
  template: bridgedbfull
  app: bridgedbfull

parameters:

- name: IMAGE_TAG
  value: orn-v1

- name: ROUTES_BASENAME
  value: prod.openrisknet.org

# -----------------------------------------------------------------------------
# BridgeDB
# -----------------------------------------------------------------------------

objects: 

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: bridgedbfull
  spec:
    replicas: 1
    selector:
      name: bridgedbfull
    template:
      metadata:
        labels:
          name: bridgedbfull
      spec:
        containers:
        - image: bigcatum/bridgedb:${IMAGE_TAG}
          name: bridgedbfull
          ports:
          - containerPort: 8080
          - containerPort: 8183

- kind: Service
  apiVersion: v1
  metadata:
    name: bridgedbfull-app
  spec:
    ports:
    - name: bridgedbfull
      port: 8183
      targetPort: 8183
    selector:
      name: bridgedbfull

- kind: Service
  apiVersion: v1
  metadata:
    name: bridgedbfull-swagger
  spec:
    ports:
    - name: swagger
      port: 8080
      targetPort: 8080
    selector:
      name: bridgedbfull


- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedbfull-app
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedbfull-app.${ROUTES_BASENAME}
    to:
      kind: Service
      name: bridgedbfull-app

- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedbfull-swagger
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedbfull-swagger.${ROUTES_BASENAME}
    path: /swagger/
    to:
      kind: Service
      name: bridgedbfull-swagger
