---

# oc process -f bridgedb.yaml | oc create -f -
# oc delete all --selector template=bridgedb

kind: Template
apiVersion: v1
metadata:
  name: bridgedb-full
  annotations:
    description: BridgeDB
    tags: bridge
labels:
  template: bridgedb-full
  app: bridgedb-full

parameters:

- name: IMAGE_TAG
  value: orn-v1

- name: ROUTES_BASENAME
  value: prod.openrisknet.org

# -----------------------------------------------------------------------------
# BridgeDB
# -----------------------------------------------------------------------------

objects: 

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: bridgedb-full
  spec:
    replicas: 1
    selector:
      name: bridgedb-full
    template:
      metadata:
        labels:
          name: bridgedb-full
      spec:
        containers:
        - image: bigcatum/bridgedb:${IMAGE_TAG}
          name: bridgedb-full
          ports:
          - containerPort: 8080
          - containerPort: 8183

- kind: Service
  apiVersion: v1
  metadata:
    name: bridgedb-full-app
  spec:
    ports:
    - name: bridgedb-full
      port: 8183
      targetPort: 8183
    selector:
      name: bridgedb-full

- kind: Service
  apiVersion: v1
  metadata:
    name: bridgedb-full-swagger
  spec:
    ports:
    - name: swagger-full
      port: 8080
      targetPort: 8080
    selector:
      name: bridgedb-full


- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedb-full-app
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedb-full-app.${ROUTES_BASENAME}
    to:
      kind: Service
      name: bridgedb-full-app

- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedb-full-swagger
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedb-full-swagger.${ROUTES_BASENAME}
    path: /swagger/
    to:
      kind: Service
      name: bridgedb-full-swagger
