---

# Preparation and project creation for the Infrastructure.

- name: Login (admin)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_admin }} -p {{ oc_admin_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

# Keycloak ImageStream

- name: Check Keycloak Image Stream
  shell: oc get is -n openshift
  register: is_result
  changed_when: False

- name: Deploy Keycloak Image Stream
  shell: >
    oc create
    -f {{ role_path }}/files/sso72-image-stream.json
    -n openshift
  when: not is_result.stdout | regex_search('^redhat-sso72-openshift\s', multiline=True)

# Infrastructure Project

- name: Login (user)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

- name: Check the Infrastructure Project
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Create the Infrastructure Project
  shell: >
    oc new-project {{ oc_infra_project }}
    --display-name='{{ oc_infra_project_display_name }}'
  when: oc_infra_project not in projects_result.stdout
