---

# Un-deploy (uninstall) the Infrastructure.
#
#  USE with EXTREME caution.

- name: Delete Infrastructure?
  pause:
    prompt: >-
      Delete the Infrastructure project?
      Press return to continue.
      Press Ctrl+c and then "a" if you've changed your mind

- name: Login (admin)
  shell: >
    oc login {{ oc_master_url }} -u {{ oc_user }} -p {{ oc_user_password }}
    --insecure-skip-tls-verify=true
  changed_when: False

# To un-deploy the infrastructure, the fastest way is to
# simply delete the project.

- name: Delete Infra Project
  shell: oc delete project/{{ oc_infra_project }}
  when:  projects_result.stdout | regex_search('^%s\s.*Active$' % oc_infra_project, multiline=True)

- name: Wait for Infra project deletion
  shell: oc get projects
  register: pj_cmd
  retries: 20
  delay: 30
  until: not pj_cmd.stdout | regex_search('^%s\s' % oc_infra_project, multiline=True)
  changed_when: False

# Delete SCC

- name: Check Infra SCC
  shell: oc get scc
  register: scc_result
  changed_when: False

- name: Delete Squonk SCC
  shell: oc delete scc/scc-squonk
  when: scc_result.stdout | regex_search('^scc-squonk', multiline=True)

