---

# oc process -f bridgedb.yaml | oc create -f -
# oc delete all --selector template=bridgedb

kind: Template
apiVersion: v1
metadata:
  name: bridgedb
  annotations:
    description: BridgeDB
    tags: bridge
labels:
  template: bridgedb
  app: bridgedb

parameters:

- name: IMAGE_TAG
  value: develop-human-2

- name: ROUTES_BASENAME
  value: prod.openrisknet.org

# -----------------------------------------------------------------------------
# BridgeDB
# -----------------------------------------------------------------------------

objects: 

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: bridgedb
  spec:
    replicas: 1
    selector:
      name: bridgedb
    template:
      metadata:
        labels:
          name: bridgedb
      spec:
        containers:
        - image: bigcatum/bridgedb:${IMAGE_TAG}
          name: bridgedb
          ports:
          - containerPort: 8080
          - containerPort: 8183

- kind: Service
  apiVersion: v1
  metadata:
    name: bridgedb
  spec:
    ports:
    - name: swagger
      port: 8080
      targetPort: 8080
    - name: bridgedb
      port: 8183
      targetPort: 8183
    selector:
      name: bridgedb

- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedb-app
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedb-app.${ROUTES_BASENAME}
    port:
      targetPort: bridgedb
    to:
      kind: Service
      name: bridgedb

- kind: Route
  apiVersion: v1
  metadata:
    name: bridgedb-swagger
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: bridgedb-swagger.${ROUTES_BASENAME}
    port:
      targetPort: swagger
    to:
      kind: Service
      name: bridgedb

