---

kind: Template
apiVersion: v1
metadata:
  name: enanomapper
  annotations:
    description: eNanoMapper contains a database with nanomaterial safety information
    tags: nanomaterials, safety, database
labels:
  template: enanomapper
  app: enanomapper

parameters:

- name: IMAGE_TAGMARIADB
  value: release
- name: IMAGE_TAGTOMCAT
  value: enm-interface-v2

- name: ROUTES_BASENAME
  value: prod.openrisknet.org

# -----------------------------------------------------------------------------
# eNanoMapper
# -----------------------------------------------------------------------------

objects: 

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: enanomapper
  spec:
    replicas: 1
    selector:
      name: enanomapper
    template:
      metadata:
        labels:
          name: enanomapper
      spec:
        containers:
        - image: bigcatum/enanomapper:${IMAGE_TAGTOMCAT}
          name: enanomapper-tomcat
          ports:
          - containerPort: 8080
        - image: ideaconsult/ambit-mariadb-test:${IMAGE_TAGMARIADB}
          name: enanomapper-mariadb
          ports:
          - containerPort: 3306

- kind: Service
  apiVersion: v1
  metadata:
    name: enanomapper-tomcat
  spec:
    ports:
    - name: enanomapper-tomcat
      port: 8080
      targetPort: 8080
    selector:
      name: enanomapper
- kind: Service
  apiVersion: v1
  metadata:
    name: enanomapper-mariadb
  spec:
    ports:
    - name: enanomapper-mariadb
      port: 3306
      targetPort: 3306
    selector:
      name: enanomapper

- kind: Route
  apiVersion: v1
  metadata:
    name: enanomapper-tomcat
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: nanomaterialdb-test.${ROUTES_BASENAME}
    path: /ambit/
    to:
      kind: Service
      name: enanomapper-tomcat
      
- kind: Route
  apiVersion: v1
  metadata:
    name: enanomapper-mariadb
    annotations:
      # Note: Set to false to avoid exhausting certificate generation request quota.
      # Change this to true when you are ready for secure the route with TLS.
      kubernetes.io/tls-acme: 'false'
  spec:
    host: enanomapper-mariadb.${ROUTES_BASENAME}
    to:
      kind: Service
      name: enanomapper-mariadb

