apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: localhost
    path: /home/data/keycloak
