---
# oc process -f bridgedb.yaml | oc create -f -
# oc delete all --selector template=bridgedb

kind: Template
apiVersion: v1
metadata:
  name: jguweka
  annotations:
    description: JGU WEKA REST service
    tags: weka,algorithm
  labels:
    template: jguweka
    app: jguweka

parameters:

- name: IMAGE_TAG
  value: OAS3
  
- name: MONGODB_TAG
  value: latest 

- name: ROUTE_NAME
  description:
    The name of the service endpoint.
  value: jguweka

- name: ROUTES_BASENAME
  description:
    The base name of the service endpoint.
    This is typically the PROD or DEV URL basename.
  value: prod.openrisknet.org

- name: TLS
  description:
    If you want TLS certificate
  value: "false"

- name: CPU_LIMIT
  description:
    Set CPU limit
  value: "2000m"

- name: CPU_REQUEST
  description:
    Set CPU request
  value: "1000m"

- name: MEMORY_LIMIT
  description:
    Set RAM limit
  value: "4Gi"

- name: MEMORY_REQUEST
  description:
    Set RAM request
  value: "2Gi"

objects:

# docker image definitions
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mongodb
  spec:
    dockerImageRepository: docker.io/gebele/mongodb
  status:
    dockerImageRepository: docker.io/gebele/mongodb
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jguweka
  spec:
    dockerImageRepository: docker.io/jguweka/jguweka
  status:
    dockerImageRepository: docker.io/jguweka/jguweka
# deployments
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: mongodb
  spec:
    strategy:
      type: Recreate
      resources: {}
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: mongodb
    template:
      metadata:
        labels:
          name: mongodb
      spec:
        containers:
        - name: mongodb
          image: docker.io/gebele/mongodb:${MONGODB_TAG}
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: true
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: jguweka
  spec:
    strategy:
      type: Recreate
      resources: {}
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: jguweka
    template:
      metadata:
        labels:
          name: jguweka
      spec:
        containers:
        - name: jguweka
          image: docker.io/jguweka/jguweka:${IMAGE_TAG}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          securityContext:
            capabilities: {}
            privileged: true
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: mongodb
  spec:
    ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 0
    selector:
      name: mongodb
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: jguweka
    annotations:
      openrisknet-static-services: http://jguweka.jguweka.svc.cluster.local:8080/openapi/openapi.json
  spec:
    ports:
    - name: jguweka
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 0
    selector:
      name: jguweka
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
# route to app
- kind: Route
  apiVersion: v1
  metadata:
    name: jguweka
    annotations:
      kubernetes.io/tls-acme: 'true'
  spec:
    host: ${ROUTE_NAME}.${ROUTES_BASENAME}
    to:
      kind: Service
      name: jguweka
    tls:
      termination: edge
  status: {}
labels:
  template: jguweka
