apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0004
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: infra-1
    path: /exports/pv-0004
