---
kind: List
apiVersion: v1
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: s2i-scipy-notebook
    labels:
      build: s2i-scipy-notebook
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-scipy-notebook-py36
    labels:
      build: s2i-scipy-notebook
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/jupyter-on-openshift/jupyter-notebooks
        ref: 2.2.2
      contextDir: scipy-notebook
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-minimal-notebook:3.6
    output:
      to:
        kind: ImageStreamTag
        name: s2i-scipy-notebook:3.6
    resources:
      limits:
        memory: 1Gi

