---
kind: List
apiVersion: v1
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: s2i-sparql-notebook
    labels:
      build: s2i-sparql-notebook
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-sparql-notebook
    labels:
      build: s2i-sparql-notebook
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/OpenRiskNet/jupyter-notebook-images
      contextDir: sparql
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-minimal-notebook:3.6
    output:
      to:
        kind: ImageStreamTag
        name: s2i-sparql-notebook:latest
    resources:
      limits:
        memory: 1Gi

