---

# The Infrastructure Persistant storage.
#
# oc process -f infra-pvc-nfs.yaml | oc create -n $OC_INFRA_PROJECT -f -
# oc delete pvc --selector template=infra-pvc-nfs -n $OC_INFRA_PROJECT

kind: Template
apiVersion: v1
metadata:
  name: infra-persistence-nfs
  annotations:
    description: Infrastructure Persistence using NFS
    tags: infra,pv,pvc
labels:
  template: infra-pvc-nfs

parameters:

- name: INFRA_NAMESPACE
  value: openrisknet-infra

- name: RABBITMQ_VOLUME_SIZE
  value: 1Gi

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: rabbitmq-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: rabbitmq
  spec:
    volumeName: pv-rabbitmq
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${RABBITMQ_VOLUME_SIZE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: postgresql
  spec:
    volumeName: pv-postgresql
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"
