---

# The Infrastructure Persistance for Minishift.
# PVs are already provided by Minishift so we only need to create PVCs
#
# oc process -f infra-pvc-minishift.yaml | oc create -n $OC_INFRA_PROJECT -f -
# oc delete pvc --selector template=infra-pvc-minishift -n $OC_INFRA_PROJECT

kind: Template
apiVersion: v1
metadata:
  name: infra-persistence-minishift
  annotations:
    description: Infrastructure Persistent Volume Claims for Minishift
    tags: infra,pvc
labels:
  template: infra-pvc-minishift

parameters:

- name: INFRA_NAMESPACE
  value: openrisknet-infra

- name: RABBITMQ_VOLUME_SIZE
  value: 1Gi

- name: POSTGRESQL_VOLUME_SIZE
  value: 50Gi

objects:

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: rabbitmq-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: rabbitmq
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${RABBITMQ_VOLUME_SIZE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql-claim
    namespace: ${INFRA_NAMESPACE}
    labels:
      application: postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${POSTGRESQL_VOLUME_SIZE}"
