apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-1
  labels:
    purpose: jupyter
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: prod-infra
    path: "/nfs-jupyter/vol1"
